In [31]:
import pandas as pd;
import numpy as np;
import matplotlib.pyplot as plt;

df = pd.read_csv(r"dataset\Raw_carbon_emission_dataset_with_Industry.csv")

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18250 entries, 0 to 18249
Data columns (total 22 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Company_ID                           18250 non-null  object
 1   Date                                 18250 non-null  object
 2   Sector                               18250 non-null  object
 3   Total_Energy_Consumption_kWh         18250 non-null  float64
 4   Renewable_Energy_Consumption_kWh     18250 non-null  float64
 5   NonRenewable_Energy_Consumption_kWh  18250 non-null  float64
 6   Production_Output_Units              18250 non-null  float64
 7   Supply_Chain_Transport_km            18250 non-null  float64
 8   Supply_Chain_Transport_Mode          18250 non-null  object
 9   Raw_Material_Usage_kg                18250 non-null  float64
 10  Carbon_Emission_tCO2e_TARGET         18250 non-null  float64
 11  Energy_Cost_USD                      18250 non-null  float64
 12  Carbon_Tax_USD                       18250 non-null  float64
 13  Process_Efficiency_Percent           18250 non-null  float64
 14  Employment_Count                     18250 non-null  int64
 15  Public_Acceptance_Index              18250 non-null  float64
 16  Carbon_Reduction_Strategy            18250 non-null  object
 17  Strategy_Implementation_Cost_USD     18250 non-null  float64
 18  Expected_Carbon_Reduction_Percent    18250 non-null  float64
 19  Expected_Renewable_Share_Percent     18250 non-null  float64
 20  Social_Impact_Score                  18250 non-null  float64
 21  Industry_Sectors                     18250 non-null  object
dtypes: float64(15), int64(1), object(6)
memory usage: 3.1+ MB

In [33]:
df.head()

,Company_ID,Date,Sector,Total_Energy_Consumption_kWh,Renewable_Energy_Consumption_kWh,NonRenewable_Energy_Consumption_kWh,Production_Output_Units,Supply_Chain_Transport_km,Supply_Chain_Transport_Mode,Raw_Material_Usage_kg,...,Carbon_Tax_USD,Process_Efficiency_Percent,Employment_Count,Public_Acceptance_Index,Carbon_Reduction_Strategy,Strategy_Implementation_Cost_USD,Expected_Carbon_Reduction_Percent,Expected_Renewable_Share_Percent,Social_Impact_Score,Industry_Sectors
0,C001,2024-01-01,Manufacturing,53751.61,12766.80,40984.81,3008.90,3814.12,Truck,51334.48,...,338.76,81.07,2128,0.77,Process Reengineering,188176.25,16.79,40.89,0.40,Steel Manufacturing
1,C001,2024-01-02,Manufacturing,170872.89,76733.84,94139.05,4062.25,1199.66,Air,17154.72,...,1073.13,69.26,855,0.77,Efficiency Upgrade,489246.31,12.57,58.19,0.86,Cement Production
2,C001,2024-01-03,Manufacturing,142777.96,75794.17,66983.79,6196.17,3670.57,Truck,56288.43,...,1390.41,90.33,3613,0.48,Carbon Tax Compliance,165061.64,12.11,68.14,0.79,Automotive Industry
3,C001,2024-01-04,Manufacturing,152532.15,20698.80,131833.35,6714.80,2903.63,Ship,21438.17,...,1942.56,79.49,3156,0.85,Efficiency Upgrade,191619.23,5.64,23.30,0.55,Logistics
4,C001,2024-01-05,Manufacturing,81647.43,46657.82,34989.61,8887.31,1916.05,Rail,37694.23,...,472.20,68.63,4915,0.47,Process Reengineering,459129.15,12.99,65.44,0.95,Steel Manufacturing

In [34]:
df.tail()

,Company_ID,Date,Sector,Total_Energy_Consumption_kWh,Renewable_Energy_Consumption_kWh,NonRenewable_Energy_Consumption_kWh,Production_Output_Units,Supply_Chain_Transport_km,Supply_Chain_Transport_Mode,Raw_Material_Usage_kg,...,Carbon_Tax_USD,Process_Efficiency_Percent,Employment_Count,Public_Acceptance_Index,Carbon_Reduction_Strategy,Strategy_Implementation_Cost_USD,Expected_Carbon_Reduction_Percent,Expected_Renewable_Share_Percent,Social_Impact_Score,Industry_Sectors
18245,C050,2024-12-26,Transport,69673.43,29071.24,40602.19,9013.46,2744.47,Truck,40063.55,...,701.61,75.53,4335,0.76,Carbon Tax Compliance,484138.46,5.48,47.70,0.83,Cement Production
18246,C050,2024-12-27,Transport,147667.28,24376.01,123291.27,6059.68,2135.77,Air,53646.80,...,1137.60,79.08,1067,0.82,Efficiency Upgrade,314618.29,7.35,28.79,0.45,Automotive Industry
18247,C050,2024-12-28,Transport,59522.00,34483.55,25038.45,2638.28,1924.02,Ship,45947.56,...,282.59,60.57,2719,0.32,Process Reengineering,189371.60,17.59,70.24,0.81,Logistics
18248,C050,2024-12-29,Transport,97234.51,12443.10,84791.41,5853.44,1279.10,Rail,30134.05,...,1001.77,67.56,4275,0.50,Carbon Tax Compliance,224436.86,6.67,23.52,0.65,Steel Manufacturing
18249,C050,2024-12-30,Transport,163312.60,84313.71,78998.89,2066.23,1446.52,Ship,72052.38,...,676.58,82.55,3302,0.79,Process Reengineering,269532.13,15.36,60.63,0.83,Cement Production

In [35]:
df['Date'].head

<bound method NDFrame.head of 0        2024-01-01
1        2024-01-02
2        2024-01-03
3        2024-01-04
4        2024-01-05
            ...
18245    2024-12-26
18246    2024-12-27
18247    2024-12-28
18248    2024-12-29
18249    2024-12-30
Name: Date, Length: 18250, dtype: object>

In [36]:
df.isnull().sum()       #No Missing Value

Company_ID                             0
Date                                   0
Sector                                 0
Total_Energy_Consumption_kWh           0
Renewable_Energy_Consumption_kWh       0
NonRenewable_Energy_Consumption_kWh    0
Production_Output_Units                0
Supply_Chain_Transport_km              0
Supply_Chain_Transport_Mode            0
Raw_Material_Usage_kg                  0
Carbon_Emission_tCO2e_TARGET           0
Energy_Cost_USD                        0
Carbon_Tax_USD                         0
Process_Efficiency_Percent             0
Employment_Count                       0
Public_Acceptance_Index                0
Carbon_Reduction_Strategy              0
Strategy_Implementation_Cost_USD       0
Expected_Carbon_Reduction_Percent      0
Expected_Renewable_Share_Percent       0
Social_Impact_Score                    0
Industry_Sectors                       0
dtype: int64

In [37]:
df.duplicated().sum()    #Zero duplicate

0

In [38]:
df['Date'] =pd.to_datetime(df['Date'])     #Conversion of Date
df['Date'].dtype

print("Start:",df['Date'].min())
print("End:",df['Date'].max())

Start: 2024-01-01 00:00:00
End: 2024-12-30 00:00:00

In [39]:
# Checking Categorial Columns
categorial_cols = df.select_dtypes(include='object').columns

for columns in categorial_cols:
    print("\n",columns)
    print(df[columns].nunique())
    print(df[columns].unique()[:20])

 Company_ID
50
['C001' 'C002' 'C003' 'C004' 'C005' 'C006' 'C007' 'C008' 'C009' 'C010'
 'C011' 'C012' 'C013' 'C014' 'C015' 'C016' 'C017' 'C018' 'C019' 'C020']

 Sector
5
['Manufacturing' 'Agriculture' 'Energy' 'Transport' 'IT']

 Supply_Chain_Transport_Mode
4
['Truck' 'Air' 'Ship' 'Rail']

 Carbon_Reduction_Strategy
4
['Process Reengineering' 'Efficiency Upgrade' 'Carbon Tax Compliance'
 'Renewable Adoption']

 Industry_Sectors
4
['Steel Manufacturing' 'Cement Production' 'Automotive Industry'
 'Logistics']

In [ ]:
# Numerical Columns                                          # No Negative Value
numeric_cols = df.select_dtypes(include='number').columns
df[numeric_cols].describe().T                                # T - rotate the table means column in row

,count,mean,std,min,25%,50%,75%,max
Total_Energy_Consumption_kWh,18250.0,124776.987158,43106.624251,50008.7300,87326.36500,124728.53000,162042.9550,199988.9100
Renewable_Energy_Consumption_kWh,18250.0,43759.097184,24291.666951,5041.2000,24455.50250,38888.00500,59545.0250,119005.2600
NonRenewable_Energy_Consumption_kWh,18250.0,81017.889975,33957.852247,20483.2600,53738.54750,77007.82000,104085.3725,179431.0200
Production_Output_Units,18250.0,5538.963915,2597.576117,1000.4700,3273.99500,5556.40000,7802.0950,9999.7800
Supply_Chain_Transport_km,18250.0,2734.813587,1300.146027,500.3800,1609.12250,2735.02000,3862.7175,4999.8900
Raw_Material_Usage_kg,18250.0,44869.415215,20110.509566,10006.5000,27439.33500,44803.63000,62291.0275,79994.4600
Carbon_Emission_tCO2e_TARGET,18250.0,32.365099,14.482041,6.8149,20.96935,30.15455,41.5204,86.5718
Energy_Cost_USD,18250.0,10600.982042,4532.900551,2524.2000,6979.21000,10001.70000,13621.3850,23880.6900
Carbon_Tax_USD,18250.0,1129.541275,590.407029,155.7400,682.40750,1012.14500,1464.8475,4211.6000
Process_Efficiency_Percent,18250.0,77.623844,10.112534,60.0000,68.88000,77.66000,86.3175,95.0000
Employment_Count,18250.0,2734.349041,1298.648265,500.0000,1603.00000,2730.00000,3853.7500,5000.0000
Public_Acceptance_Index,18250.0,0.624569,0.187841,0.3000,0.46000,0.62500,0.7900,0.9500
Strategy_Implementation_Cost_USD,18250.0,299333.028470,115674.898008,100052.3400,199132.37250,297477.13000,399960.9325,499881.1700
Expected_Carbon_Reduction_Percent,18250.0,15.067031,5.794350,5.0000,10.04000,15.10000,20.0700,25.0000
Expected_Renewable_Share_Percent,18250.0,47.637350,15.086466,15.2500,35.24000,47.66000,60.1900,79.9400
Social_Impact_Score,18250.0,0.674542,0.159451,0.4000,0.54000,0.68000,0.8100,0.9500

In [ ]:
#Outlier 
Q1 = df["Carbon_Emission_tCO2e_TARGET"].quantile(0.25)
Q2 = df["Carbon_Emission_tCO2e_TARGET"].quartile(0.75)